# Generated by Django 4.1.4 on 2023-01-16 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_content_alter_post_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
