# Generated by Django 4.1.4 on 2023-01-16 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=250, unique_for_date="published"
            ),
        ),
    ]
